### ISSUE TITLE
Navbar rendering problem

### ISSUE THREAD

**Issue by kyle-fredrickson** [linqs/linqs-website#2]
When the width of the window is small the navbar in the header collapses, but does not render correctly.
<img width="562" alt="Screen Shot 2020-07-13 at 5 03 05 PM" src="https://user-images.githubusercontent.com/11300846/87366122-c7d3c980-c52c-11ea-8307-7b848e27f162.png">

**Comment by bterrific2008** [comment]
I think the issue is caused by the navigation links inheriting `header.site-header a` css style. This sets their font to be white, which matches the background.

**Comment by eriq-augustine** [comment]
Thanks for looking at this, Bryan.
Seems to be more an issue with the background color rather than the text color (since we want the text color the be white).
Go ahead and tackle this one, Bryan.
